"""empty message

Revision ID: 3ff9fa834113
Revises: 
Create Date: 2023-04-28 13:13:22.176107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ff9fa834113'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_slot',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('effective_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    postgresql.ExcludeConstraint(('tstzrange(effective_time, expiry_time)', '&&'), using='gist'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_slot_effective_time'), 'time_slot', ['effective_time'], unique=False)
    op.create_index(op.f('ix_time_slot_expiry_time'), 'time_slot', ['expiry_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_slot_expiry_time'), table_name='time_slot')
    op.drop_index(op.f('ix_time_slot_effective_time'), table_name='time_slot')
    op.drop_table('time_slot')
    # ### end Alembic commands ###
